### ISSUE TITLE
do you need help

### ISSUE THREAD

**Issue by jesse-osiecki** [LineageOS-MediaTek/android_device_unihertz_jellypro#1]
I am interested in helping to get this device tree working, what is outstanding and left to do ?

**Comment by SamarV-121** [comment]
https://samarv-121.blogspot.com/2018/06/rom712unofficialbeta-resurrectionremix.html

Almost everything is fixed except RIL and Cam

**Comment by jesse-osiecki** [comment]
that's amazing, thank you.
