### ISSUE TITLE
Prebuilt kernel origin

### ISSUE THREAD

**Issue by samueldr** [LineageOS-MediaTek/android_device_unihertz_jellypro#2]
Hi,

I am assuming the prebuilt kernel was extracted from a Jelly Pro ROM. Which revision is it? Do you track the OEM updates and update the kernel accordingly? (It may be of interest to add the OEM ROM revision used when extracting the kernel.)

It would also be helpful if you described how to extract it, to ensure replication of results. (This may also help for other MediaTek devices not yet ported.)

**Comment by SamarV-121** [comment]
many guides are avail* for extracting kernel from boot
just google it once ;)
